Atmosphere-ICT283: AtmosphereLogTypes.h File Reference
AtmosphereLogTypes.h File Reference
#include "date.h"
#include "mytime.h"
#include "vector.h"
Classes
struct AtmosRecType
Represents a atmospheric data record containing date, wind speed, wind temperature and solar radiation.
Typedefs
typedef Vector< AtmosRecType > AtmosLogType
A Vector container storing multiple AtmosRecType records.
Functions
bool operator< (const AtmosRecType &lhs, const AtmosRecType &rhs)
Less-than operator for comparing two AtmosRecType objects.
bool operator> (const AtmosRecType &lhs, const AtmosRecType &rhs)
Greater-than operator for comparing two AtmosRecType objects.
bool operator== (const AtmosRecType &lhs, const AtmosRecType &rhs)
Comparison operator for comparing two AtmosRecType objects.
Typedef Documentation
AtmosLogType
typedef Vector<AtmosRecType> AtmosLogType
A Vector container storing multiple AtmosRecType records.
Definition at line 24 of file AtmosphereLogTypes.h.
Function Documentation
operator<()
bool operator< (const AtmosRecType & lhs, const AtmosRecType & rhs)
Less-than operator for comparing two AtmosRecType objects.
Compares two AtmosRecType objects, comparing date, time, speed, temperature, and solar_rad in order, returning true if the left hand side is less than the right hand side.
Parameters
lhs - The left-hand side AtmosRecType object.
rhs - The right-hand side AtmosRecType object.
Returns
True if any of lhs data members are less than rhs data members.
Precondition
lhs and rhs are valid AtmosRecType struct objects with valid values.
Postcondition
lhs and rhs remain unchanged.
Definition at line 7 of file AtmosphereLogTypes.cpp.
{
    if (!(lhs.date == rhs.date))
    {
        return lhs.date < rhs.date;
    }
    if (!(lhs.time == rhs.time))
    {
        return lhs.time < rhs.time;
    }
    if (!CompareFloats(lhs.speed, rhs.speed))
    {
        return lhs.speed < rhs.speed;
    }
    if (!CompareFloats(lhs.temperature, rhs.temperature))
    {
        return lhs.temperature < rhs.temperature;
    }
    if (!CompareFloats(lhs.solar_rad, rhs.solar_rad))
    {
        return lhs.solar_rad < rhs.solar_rad;
    }
    return false;
}
References CompareFloats(), AtmosRecType::date, operator<(), operator<(), operator==(), operator==(), AtmosRecType::solar_rad, AtmosRecType::speed, AtmosRecType::temperature, and AtmosRecType::time.
operator==()
bool operator== (const AtmosRecType & lhs, const AtmosRecType & rhs)
Comparison operator for comparing two AtmosRecType objects.
Compares two AtmosRecType objects, comparing date, time, speed, temperature, and solar_rad in order, returning true if the left hand side equal to the right hand side.
Parameters
lhs - The left-hand side AtmosRecType object.
rhs - The right-hand side AtmosRecType object.
Returns
True if all of lhs data members are equal to rhs data members.
Precondition
lhs and rhs are valid AtmosRecType struct objects with valid values.
Postcondition
lhs and rhs remain unchanged.
Definition at line 71 of file AtmosphereLogTypes.cpp.
{
    return lhs.date == rhs.date &&
           lhs.time == rhs.time &&
           CompareFloats(lhs.speed, rhs.speed) &&
           CompareFloats(lhs.temperature, rhs.temperature) &&
           CompareFloats(lhs.solar_rad, rhs.solar_rad);
}
References CompareFloats(), AtmosRecType::date, operator==(), operator==(), AtmosRecType::solar_rad, AtmosRecType::speed, AtmosRecType::temperature, and AtmosRecType::time.
operator>()
bool operator> (const AtmosRecType & lhs, const AtmosRecType & rhs)
Greater-than operator for comparing two AtmosRecType objects.
Compares two AtmosRecType objects, comparing date, time, speed, temperature, and solar_rad in order, returning true if the left hand side is greater than the right hand side.
Parameters
lhs - The left-hand side AtmosRecType object.
rhs - The right-hand side AtmosRecType object.
Returns
True if any of lhs data members are greater than rhs data members.
Precondition
lhs and rhs are valid AtmosRecType struct objects with valid values.
Postcondition
lhs and rhs remain unchanged.
Definition at line 39 of file AtmosphereLogTypes.cpp.
{
    if (!(lhs.date == rhs.date))
    {
        return lhs.date > rhs.date;
    }
    if (!(lhs.time == rhs.time))
    {
        return lhs.time > rhs.time;
    }
    if (!CompareFloats(lhs.speed, rhs.speed))
    {
        return lhs.speed > rhs.speed;
    }
    if (!CompareFloats(lhs.temperature, rhs.temperature))
    {
        return lhs.temperature > rhs.temperature;
    }
    if (!CompareFloats(lhs.solar_rad, rhs.solar_rad))
    {
        return lhs.solar_rad > rhs.solar_rad;
    }
    return false;
}
References CompareFloats(), AtmosRecType::date, operator==(), operator==(), operator>(), operator>(), AtmosRecType::solar_rad, AtmosRecType::speed, AtmosRecType::temperature, and AtmosRecType::time.