Atmosphere-ICT283: Calc.h File Reference
Calc.h File Reference
#include "vector.h"
#include <math.h>
#include <iostream>
Functions
template<class T>
T CalculateMean (const Vector< T > &vec, int total)
Calculates the mean (average) of a vector of values.
template<class T>
float CalculateStandardDeviation (const Vector< T > &vec, int N, float mean)
Calculates the sample standard deviation of a vector of values.
template<class T>
T CalculateTotal (const Vector< T > &vec, int size)
Calculates the total sum of a vector of values.
template<class T>
float sPCC (const Vector< T > &x, const Vector< T > &y)
Calculates the Sample Pearson Correlation Coefficient (sPCC) between two vectors.
template<class T>
bool ValidateVectorSizes (const Vector< T > &x, const Vector< T > &y)
Validates that two vectors are non-empty and of equal size.
template<class T>
float CalculateCovariance (const Vector< T > &x, const Vector< T > &y, float meanX, float meanY)
Computes the covariance component for sPCC between two vectors.
template<class T>
float CalculateVariance (const Vector< T > &vec, float mean)
Calculates the sum of squared differences (variance numerator) of a vector.
template<class T>
float MAD (const Vector< T > &vec, int size)
Calculates the Mean Absolute Deviation (MAD) of a vector of values.
bool CompareFloats (float a, float b)
Compare two floating-point speed values to check if they are approximately equal.
Function Documentation
CalculateCovariance()
template<class T> float CalculateCovariance (const Vector< T > & x, const Vector< T > & y, float meanX, float meanY)
Computes the covariance component for sPCC between two vectors.
Template Parameters
T The numeric type stored in the vectors.
Parameters
x The first data vector.
y The second data vector.
meanX The precomputed mean of vector x.
meanY The precomputed mean of vector y.
Returns
The sum of products of differences from the means.
Definition at line 168 of file Calc.h.
{
    float sumXY = 0;
    for (int i = 0; i < x.GetSize(); i++) {
        float xDiff = x[i] - meanX;
        float yDiff = y[i] - meanY;
        sumXY += xDiff * yDiff;
    }
    return sumXY;
}
CalculateMean()
template<class T> T CalculateMean (const Vector< T > & vec, int total)
Calculates the mean (average) of a vector of values.
This templated function takes in a vector of any numeric type and calculates the mean by summing all elements and dividing by the total number.
Template Parameters
T - The type of the elements stored in the vector (for example float or int).
Parameters
vec - A vector containing elements of type T.
total - The number of elements to include in the mean calculation.
Returns
The mean of the elements in the vector.
Precondition
total > 0 and all elements in vec must be valid numeric values.
Postcondition
Returns the calculated mean of type T.
Definition at line 26 of file Calc.h.
{
    T sum = 0;
    for (int i = 0; i < total; i++)
    {
        sum += vec[i];
    }
    return sum/total;
}
CalculateStandardDeviation()
template<class T> float CalculateStandardDeviation (const Vector< T > & vec, int N, float mean)
Calculates the sample standard deviation of a vector of values.
This templated function uses the sample standard deviation formula, where the variance is divided by (N - 1). It assumes a precalculated mean is provided.
Template Parameters
T - The type of the elements stored in the vector (e.g., float, int).
Parameters
vec - A vector containing elements of type T.
N - The number of elements to include in the standard deviation calculation.
mean - The precalculated mean of the vector elements.
Returns
The sample standard deviation of the elements in the vector.
Precondition
N > 1 and all elements in vec must be valid numeric values.
Postcondition
Returns the sample standard deviation.
Definition at line 53 of file Calc.h.
{
    T sum = 0;
    for (int i = 0; i < N; ++i)
    {
        T diff = vec[i] - mean;
        sum += diff * diff;
    }
    return sqrt(sum / (N - 1));
}
CalculateTotal()
template<class T> T CalculateTotal (const Vector< T > & vec, int size)
Calculates the total sum of a vector of values.
This templated function computes the total sum of the elements in the vector.
Template Parameters
T - The type of the elements stored in the vector (e.g., float, int).
Parameters
vec - A vector containing elements of type T.
size - The number of elements to include in the summation.
Returns
The total of all elements in the vector.
Precondition
size >= 0 and all elements in vec must be valid numeric values.
Postcondition
Returns the total of type T.
Definition at line 79 of file Calc.h.
{
    T sum = 0;
    for (int i = 0; i < size; ++i)
    {
        sum += vec[i];
    }
    return sum;
}
CalculateVariance()
template<class T> float CalculateVariance (const Vector< T > & vec, float mean)
Calculates the sum of squared differences (variance numerator) of a vector.
This function computes the variance numerator (∑(x - mean)²), useful for correlation or standard deviation.
Template Parameters
T The numeric type of the vector elements.
Parameters
vec The data vector.
mean The mean of the vector's values.
Returns
The sum of squared differences from the mean.
Definition at line 191 of file Calc.h.
{
    float sumSquaredDiff = 0;
    for (int i = 0; i < vec.GetSize(); i++) {
        float diff = vec[i] - mean;
        sumSquaredDiff += diff * diff;
    }
    return sumSquaredDiff;
}
CompareFloats()
bool CompareFloats (float a, float b)
Compare two floating-point speed values to check if they are approximately equal.
This function compares two float values and returns true if they are within a small tolerance of each other to account for floating-point precision.
Parameters
a - The first float value.
b - The second float value to compare against.
Returns
true if the floats are considered equal within tolerance; false otherwise.
Precondition
The inputs a and b are valid floating-point numbers (not NaN or infinity).
Postcondition
Returns a boolean indicating whether a and b are within tolerance.
Definition at line 7 of file Calc.cpp.
{
    float epsilon = 0.5f;
    return std::fabs(a - b) < epsilon;
}
Referenced by operator<(), operator==(), and operator>().
MAD()
template<class T> float MAD (const Vector< T > & vec, int size)
Calculates the Mean Absolute Deviation (MAD) of a vector of values.
This templated function computes the Mean Absolute Deviation (MAD), which is the average of the absolute differences between each value and the mean. It is a measure of dispersion in the dataset and is less sensitive to outliers than standard deviation.
Template Parameters
T - The type of the elements stored in the vector (e.g., float, int).
Parameters
vec - A vector containing elements of type T.
size - The number of elements to include in the MAD calculation.
Returns
The mean absolute deviation of the elements in the vector.
Precondition
size > 0 and all elements in vec must be valid numeric values.
Postcondition
Returns the mean absolute deviation as a float.
Definition at line 217 of file Calc.h.
{
    T sum = 0;
    float mean = CalculateMean(vec, size);
    for (int i = 0; i < size; i++)
    {
        sum += std::abs(vec[i] - mean);
    }
    return sum / size;
}
sPCC()
template<class T> float sPCC (const Vector< T > & x, const Vector< T > & y)
Calculates the Sample Pearson Correlation Coefficient (sPCC) between two vectors.
This function measures the linear correlation between two data sets by computing the covariance and variances, then applying the sPCC formula.
Template Parameters
T The numeric type stored in the vectors (e.g., float).
Parameters
x The first data vector.
y The second data vector.
Returns
The correlation coefficient between -1.0 and 1.0, or -1 if the inputs are invalid.
Precondition
x and y must be non-empty and of equal size.
Postcondition
No modification to input vectors.
Definition at line 105 of file Calc.h.
{
    if (!ValidateVectorSizes(x, y))
    {
        return -1;
    }
    float meanX = CalculateMean(x, x.GetSize());
    float meanY = CalculateMean(y, y.GetSize());
    float sumXY = CalculateCovariance(x, y, meanX, meanY);
    float sumX2 = CalculateVariance(x, meanX);
    float sumY2 = CalculateVariance(y, meanY);
    float sqrtX2 = sqrt(sumX2);
    float sqrtY2 = sqrt(sumY2);
    float denom = sqrtX2 * sqrtY2;
    if (denom == 0)
    {
        return 0;
    }
    return sumXY / denom;
}
ValidateVectorSizes()
template<class T> bool ValidateVectorSizes (const Vector< T > & x, const Vector< T > & y)
Validates that two vectors are non-empty and of equal size.
Template Parameters
T The type of the vector elements.
Parameters
x The first vector.
y The second vector.
Returns
true if both vectors are valid and compatible for paired operations.
false if vectors are empty or sizes mismatch.
Definition at line 143 of file Calc.h.
{
    if (x.GetSize() != y.GetSize()) {
        std::cout << "X and Y are not the same size.\n";
        return false;
    }
    if (x.GetSize() == 0 || y.GetSize() == 0) {
        std::cout << "Vectors are empty.\n";
        return false;
    }
    return true;
}