Atmosphere-ICT283: Calc.cpp File Reference
Calc.cpp File Reference
#include "calc.h"
#include "atmospherelogtypes.h"
#include <math.h>
Functions
bool CompareFloats (float a, float b)
Compare two floating-point speed values to check if they are approximately equal.
Function Documentation
CompareFloats()
bool CompareFloats (float a, float b)
Compare two floating-point speed values to check if they are approximately equal.
This function compares two float values and returns true if they are within a small tolerance of each other to account for floating-point precision.
Parameters
a - The first float value.
b - The second float value to compare against.
Returns
true if the floats are considered equal within tolerance; false otherwise.
Precondition
The inputs a and b are valid floating-point numbers (not NaN or infinity).
Postcondition
Returns a boolean indicating whether a and b are within tolerance.
Definition at line 7 of file Calc.cpp.
{
    float epsilon = 0.5f;
    return std::fabs(a - b) < epsilon;
}
Referenced by operator<(), operator==(), and operator>().