Atmosphere-ICT283: FileIO.h File Reference
FileIO.h File Reference
#include "atmospherelogtypes.h"
#include "vector.h"
#include "BST.h"
#include <map>
#include <string>
#include <fstream>
Functions
bool LoadAtmosphereData (AtmosLogType &atmosData)
Loads atmospheric data from multiple input files listed in data_source.txt.
void ReadAtmosphereData (std::ifstream &file, AtmosLogType &atmosData)
Reads atmospheric data from a file into a structured vector.
bool GetColumnIndices (std::string &headerLine, int &wastIndex, int &sIndex, int &tIndex, int &srIndex)
Finds the column indices of WAST, S, T, and SR from the header line.
void ReadRowData (std::string &line, std::string &wastData, int wastIndex, std::string &sData, int sIndex, std::string &tData, int tIndex, std::string &srData, int srIndex)
Extracts required field values from a CSV line based on column indices.
void ParseDateRecord (std::string dateStr, Date &d)
Parse a date string into a Date object.
void ParseTimeRecord (std::string timeStr, MyTime &t)
Parse a time string into a Time object.
void WriteAtmosphereData (std::ofstream &file, const AtmosLogType &atmosData)
Writes atmospheric data to a CSV output file.
void TransferToBSTAndMap (const AtmosLogType &atmosData, BST< AtmosRecType > &bstData, std::map< int, AtmosLogType > &mapData)
Transfers data from AtmosRecType vector to BST and map structures.
void BuildBalancedBST (BST< AtmosRecType > &bstData, const AtmosLogType &sortedData, int start, int end)
Recursively builds a height-balanced Binary Search Tree from sorted atmospheric data.
Function Documentation
BuildBalancedBST()
void BuildBalancedBST (BST< AtmosRecType > & bstData, const AtmosLogType & sortedData, int start, int end)
Recursively builds a height-balanced Binary Search Tree from sorted atmospheric data.
This function uses a recursive divide-and-conquer strategy to construct a balanced BST by inserting the middle element of the current range, then repeating the process for the left and right subranges.
Parameters
bstData A reference to the BST where the balanced nodes will be inserted.
sortedData A const reference to a sorted AtmosLogType (vector of AtmosRecType).
start The starting index of the current range in the sorted vector.
end The ending index of the current range in the sorted vector.
Returns
void
Precondition
sortedData must be sorted by the desired BST ordering criteria (e.g., Date/Time).
Postcondition
bstData is populated with a balanced BST containing all elements from sortedData[start] to sortedData[end].
Definition at line 281 of file FileIO.cpp.
{
    if (start > end)
    {
        return;
    }
    int mid = (start + end) / 2;
    bstData.Insert(sortedData[mid]);
    BuildBalancedBST(bstData, sortedData, start, mid - 1);
    BuildBalancedBST(bstData, sortedData, mid + 1, end);
}
References BuildBalancedBST().
Referenced by BuildBalancedBST().
GetColumnIndices()
bool GetColumnIndices (std::string & headerLine, int & wastIndex, int & sIndex, int & tIndex, int & srIndex)
Finds the column indices of WAST, S, T, and SR from the header line.
Parses the header row of the CSV file to determine the positions of key fields. Ensures all expected columns exist before data extraction begins.
Parameters
headerLine - The header line from the input file.
wastIndex - Output parameter to store the index of the WAST column.
sIndex - Output parameter to store the index of the S (Speed) column.
tIndex - Output parameter to store the index of the T (Temperature) column.
srIndex - Output parameter to store the index of the SR (Solar Radiation) column.
Returns
true if all required columns are found; false otherwise.
Precondition
headerLine must be a valid CSV-formatted line containing column headers.
Postcondition
wastIndex, sIndex, tIndex, and srIndex are updated with appropriate values if found.
Definition at line 122 of file FileIO.cpp.
{
    wastIndex = -1;
    sIndex = -1;
    tIndex = -1;
    srIndex = -1;
    int columnIndex = 0, start = 0, end;
    std::string data = "";
    while((end = headerLine.find(',', start)) != -1)
    {
        data = headerLine.substr(start, end - start);
        if (data == "WAST")
        {
            wastIndex = columnIndex;
        }
        else if (data == "S")
        {
            sIndex = columnIndex;
        }
        else if (data == "T")
        {
            tIndex = columnIndex;
        }
        else if (data == "SR")
        {
            srIndex = columnIndex;
        }
        start = end + 1;
        columnIndex++;
    }
    // Check for last column (doesnt have a comma)
    data = headerLine.substr(start);
    if (data == "WAST")
    {
        wastIndex = columnIndex;
    }
    else if (data == "S")
    {
        sIndex = columnIndex;
    }
    else if (data == "T")
    {
        tIndex = columnIndex;
    }
    else if (data == "SR")
    {
        srIndex = columnIndex;
    }
    return (wastIndex != -1 && sIndex != -1 && tIndex != -1 && srIndex != -1);
}
LoadAtmosphereData()
bool LoadAtmosphereData (AtmosLogType & atmosData)
Loads atmospheric data from multiple input files listed in data_source.txt.
This function opens the "data/data_source.txt" file and reads filenames line by line. For each listed file, it attempts to open and parse atmospheric records using ReadAtmosphereData(). All valid data is appended to the provided AtmosLogType vector.
Parameters
atmosData A reference to an AtmosLogType (i.e., Vector of AtmosRecType) where all parsed records are stored.
Returns
true if data_source.txt was successfully opened and at least one input file was attempted, and false if data_source.txt could not be opened.
Precondition
data/data_source.txt must exist and contain valid input filenames, one per line.
Postcondition
atmosData contains all valid parsed records from the listed files. Invalid files are skipped with a warning.
Definition at line 11 of file FileIO.cpp.
{
    // Get input filenames from data_source.txt
    std::ifstream src("data/data_source.txt");
    if (!src)
    {
        std::cout << "Unable to open data_source.txt\n";
        return false;
    }
    // Collect data from input files
    std::string inFilename;
    while (std::getline(src, inFilename))
    {
        std::ifstream inFile("data/" + inFilename);
        if (!inFile)
        {
            std::cout << "Unable to open input file " + inFilename << std::endl;
        }
        else
        {
            ReadAtmosphereData(inFile, atmosData);
            inFile.close();
        }
    }
    src.close();
    return true;
}
ParseDateRecord()
void ParseDateRecord (std::string dateStr, Date & d)
Parse a date string into a Date object.
This function converts a date string (e.g., "15/03/2015") into a Date struct by extracting the day, month, and year.
Parameters
dateStr - The input date string.
d - Reference to a Date object that will be populated.
Returns
void
Precondition
The date string must be in the format "DD/MM/YYYY".
Postcondition
The Date object contains the parsed day, month, and year.
Definition at line 222 of file FileIO.cpp.
{
    int firstSlashInd = dateStr.find('/');
    int secondSlashInd = dateStr.find('/', firstSlashInd + 1);
    int day = stoi(dateStr.substr(0, firstSlashInd));
    int month = stoi(dateStr.substr(firstSlashInd + 1, secondSlashInd - firstSlashInd - 1));
    int year = stoi(dateStr.substr(secondSlashInd + 1));
    d.SetDay(day);
    d.SetMonth(month);
    d.SetYear(year);
}
References Date::SetDay(), Date::SetMonth(), and Date::SetYear().
ParseTimeRecord()
void ParseTimeRecord (std::string timeStr, MyTime & t)
Parse a time string into a Time object.
This function converts a time string (e.g., "14:30") into a Time struct by extracting the hour and minute values.
Parameters
timeStr - The input time string.
t - Reference to a MyTime object that will be populated.
Returns
void
Precondition
The time string must be in the format "HH:MM".
Postcondition
The MyTime object contains the parsed hour and minute.
Definition at line 238 of file FileIO.cpp.
{
    int colonInd = timeStr.find(':');
    int hour = stoi(timeStr.substr(0, colonInd));
    int minute = stoi(timeStr.substr(colonInd + 1));
    t.SetHour(hour);
    t.SetMinute(minute);
}
References MyTime::SetHour(), and MyTime::SetMinute().
ReadAtmosphereData()
void ReadAtmosphereData (std::ifstream & file, AtmosLogType & atmosData)
Reads atmospheric data from a file into a structured vector.
Parses the specified file stream to extract date, time, wind speed, temperature, and solar radiation. Handles missing or invalid data by setting those values to -1.0f. Extracted values are stored in AtmosRecType objects which are inserted into a Vector passed as a reference parameter.
Parameters
file - Input file stream containing atmospheric CSV data.
atmosData - A reference to a vector containing the parsed atmospheric records.
Precondition
file must be open and contain valid CSV data with appropriate headers.
Postcondition
All valid records from the file are parsed and stored in the returned vector.
Definition at line 42 of file FileIO.cpp.
{
    std::string line;
    int wastIndex, sIndex, tIndex, srIndex;
    // Read entire header line and find column indices of WAST, S, T and SR
    // If the columns don't exist, print error
    if (!std::getline(file, line) || !GetColumnIndices(line, wastIndex, sIndex, tIndex, srIndex))
    {
        std::cout << "Column missing in data file" << std::endl;
        return;
    }
    // Using found column indices, parse and store data from each row
    while (std::getline(file, line))
    {
        std::string wastData = "", sData = "", tData = "", srData = "";
        ReadRowData(line, wastData, wastIndex, sData, sIndex, tData, tIndex, srData, srIndex);
        if (!wastData.empty())
        {
            // Parse and store WAST data (date and time)
            int space = wastData.find(' ');
            Date dateTemp;
            ParseDateRecord(wastData.substr(0, space), dateTemp);
            MyTime timeTemp;
            ParseTimeRecord(wastData.substr(space + 1), timeTemp);
            // Parse and store S data
            float speedTemp;
            if (!sData.empty() && sData != "N/A")
            {
                speedTemp = stof(sData);
            }
            else
            {
                speedTemp = -1.0f;
            }
            // Parse and store T data
            float temperatTemp;
            if (!tData.empty() && tData != "N/A")
            {
                temperatTemp = stof(tData);
            }
            else
            {
                temperatTemp = -1.0f;
            }
            // Parse and store SR data
            float srTemp;
            if (!srData.empty() && srData != "N/A")
            {
                srTemp = stof(srData);
            }
            else
            {
                srTemp = -1.0f;
            }
            // Store atmosphere data into struct
            AtmosRecType a;
            a.date = dateTemp;
            a.time = timeTemp;
            a.speed = speedTemp;
            a.temperature = temperatTemp;
            a.solar_rad = srTemp;
            // Insert atmosphere data into temporary vector
            atmosData.PushBack(a);
        }
    }
}
References AtmosRecType::date, AtmosRecType::solar_rad, AtmosRecType::speed, AtmosRecType::temperature, and AtmosRecType::time.
ReadRowData()
void ReadRowData (std::string & line, std::string & wastData, int wastIndex, std::string & sData, int sIndex, std::string & tData, int tIndex, std::string & srData, int srIndex)
Extracts required field values from a CSV line based on column indices.
Parses a single line from the input CSV file to extract values for WAST, Speed, Temperature, and Solar Radiation. The extracted values are returned via reference parameters.
Parameters
line - A line of data from the CSV file.
wastData - Reference to store the extracted WAST (Date and Time) string.
wastIndex - Column index for WAST.
sData - Reference to store the extracted Speed string.
sIndex - Column index for Speed.
tData - Reference to store the extracted Temperature string.
tIndex - Column index for Temperature.
srData - Reference to store the extracted Solar Radiation string.
srIndex - Column index for Solar Radiation.
Precondition
line must be a valid CSV-formatted string containing enough columns.
Postcondition
wastData, sData, tData, and srData are updated with values if their respective columns exist.
Definition at line 179 of file FileIO.cpp.
{
    std::string data = "";
    int start = 0, end;
    // Extract data from relevant column
    for (int columnIndex = 0; columnIndex < 18 && (wastData.empty() || sData.empty() || tData.empty() || srData.empty()); columnIndex++)
    {
        end = line.find(',', start);
        if (end == -1)
        {
            data = line.substr(start);
        }
        else
        {
            data = line.substr(start, end - start);
        }
        if (columnIndex == wastIndex)
        {
            wastData = data;
        }
        else if (columnIndex == sIndex)
        {
            sData = data;
        }
        else if (columnIndex == tIndex)
        {
            tData = data;
        }
        else if (columnIndex == srIndex)
        {
            srData = data;
        }
        start = (end == -1) ? line.size() : end + 1;
    }
}
TransferToBSTAndMap()
void TransferToBSTAndMap (const AtmosLogType & atmosData, BST< AtmosRecType > & bstData, std::map< int, AtmosLogType > & mapData)
Transfers data from AtmosRecType vector to BST and map structures.
This method transfers the data from the AtmosRecType vector (AtmosLogType) to a BST and an std::map. It orders the data into the map using the month integer as the key.
Parameters
atmosData - the reference to the AtmosRecType vector, AtmosLogType.
bstData - the reference to the AtmosRecType Binary Search Tree.
mapData - the reference to the AtmosLogType Map with month integers as the keys.
Returns
void
Precondition
atmosData, bstData and mapData are valid and properly constructed.
Postcondition
bstData contains all records from atmosData. mapData contains records indexed by month.
Definition at line 266 of file FileIO.cpp.
{
    for (int i = 0; i < atmosData.GetSize(); i++)
    {
        const AtmosRecType & rec = atmosData[i];
        mapData[rec.date.GetYear()].PushBack(rec);
    }
    AtmosLogType sortedData = atmosData;
    MergeSort(sortedData, 0, sortedData.GetSize() - 1);
    BuildBalancedBST(bstData, sortedData, 0, sortedData.GetSize() - 1);
}
References AtmosRecType::date, and Date::GetYear().
WriteAtmosphereData()
void WriteAtmosphereData (std::ofstream & file, const AtmosLogType & atmosData)
Writes atmospheric data to a CSV output file.
Writes the contents of the AtmosLogType vector to a CSV file with columns for Date, Time, Speed, Temperature, and Solar Radiation.
Parameters
file - Output file stream to write to.
atmosData - Vector containing atmospheric data records.
Precondition
file must be open and ready for writing.
Postcondition
The output file contains a formatted CSV representation of the atmospheric data.
Definition at line 251 of file FileIO.cpp.
{
    file << "Date,Time,Speed,Temperature,Solar Radiation\n";
    for (int i = 0; i < atmosData.GetSize(); i++)
    {
        file << atmosData[i].date.GetDay() << "/" << atmosData[i].date.GetMonth() << "/" << atmosData[i].date.GetYear() << ","
             << atmosData[i].time.GetHour() << ":" << atmosData[i].time.GetMinute() << ","
             << atmosData[i].speed << ","
             << atmosData[i].temperature << ","
             << atmosData[i].solar_rad << std::endl;
    }
}