Atmosphere-ICT283: Menu.cpp File Reference
Menu.cpp File Reference
#include "menu.h"
#include "atmospherelogtypes.h"
#include "calc.h"
#include "vector.h"
#include "BST.h"
#include "Collector.h"
#include "utils.h"
#include "fileio.h"
#include <map>
#include <iostream>
#include <iomanip>
#include <string>
Functions
void RunMenuLoop (const BST< AtmosRecType > &atmos_bst, const std::map< int, AtmosLogType > &atmos_map)
Runs the menu loop and processes the user's choice.
int DisplayMenu ()
Displays the main menu and prompts the user for a selection.
void DisplayWindSpeedAvgAndStdDev (const std::map< int, AtmosLogType > &data)
Display wind speed average and standard deviation.
void DisplayTempAvgAndStdDev (const std::map< int, AtmosLogType > &data)
Display temperature average and stddev for each month of a given year.
void CalculateAndDisplaySPCC (const BST< AtmosRecType > &data)
Calculates and displays Sample Pearson Correlation Coefficients for a specified month.
void ExportToWindTempSolarCSV (const std::map< int, AtmosLogType > &data)
Export wind, temperature, and solar radiation data to file.
void PrintDateAndTime (const AtmosRecType &a)
Prints the date and time from a given AtmosRecType record.
int PromptMonth ()
Prompts the user to enter a valid month (1-12).
int PromptYear ()
Prompts the user to enter a year.
static const std::string & MonthToString (int monthNum)
void GatherSpeedValues (const AtmosLogType &source, Vector< float > &vec, int month)
Gathers wind speed values for a specified month.
void GatherTempValues (const AtmosLogType &source, Vector< float > &vec, int month)
Gathers air temperature values for a specific month.
void GatherSolarRadValues (const AtmosLogType &source, Vector< float > &vec, int month)
Gathers solar radiation values for a specific year and optional month.
Function Documentation
CalculateAndDisplaySPCC()
void CalculateAndDisplaySPCC (const BST< AtmosRecType > & data)
Calculates and displays Sample Pearson Correlation Coefficients for a specified month.
This function prompts the user for a target month and calculates three Sample Pearson Correlation Coefficients:
Wind Speed vs Air Temperature (S_T)
Wind Speed vs Solar Radiation (S_R)
Air Temperature vs Solar Radiation (T_R)
It uses the static Collector class to gather filtered data from the provided BST of atmospheric records. Data is collected via in-order traversal using function pointers to Collector methods. Each correlation coefficient is then computed using the sPCC methods and printed to the console.
Parameters
data A constant reference to a BST of AtmosRecType records, representing all atmospheric data.
Returns
void
Precondition
The BST must be populated with valid AtmosRecType data. The Collector class must be correctly implemented.
Postcondition
No changes to the BST. Output is printed to standard output. Collector’s internal state is reset between each correlation.
Definition at line 146 of file Menu.cpp.
{
    int month = PromptMonth();
    // Calculate ST
    Collector::Clear();
    Collector::SetTargetMonth(month);
    data.InOrderTraversal(Collector::CollectST);
    float st = sPCC(Collector::GetSpeedVec(), Collector::GetTempVec());
    // Calculate SR
    Collector::Clear();
    Collector::SetTargetMonth(month);
    data.InOrderTraversal(Collector::CollectSR);
    float sr = sPCC(Collector::GetSpeedVec(), Collector::GetRadVec());
    // Calculate TR
    Collector::Clear();
    Collector::SetTargetMonth(month);
    data.InOrderTraversal(Collector::CollectTR);
    float tr = sPCC(Collector::GetTempVec(), Collector::GetRadVec());
    std::cout << std::fixed << std::setprecision(2);
    std::cout << "Sample Pearson Correlation Coefficient for " << MonthToString(month) << std::endl;
    std::cout << "S_T: " << st << std::endl;
    std::cout << "S_R: " << sr << std::endl;
    std::cout << "T_R: " << tr << std::endl;
}
References Collector::Clear(), Collector::CollectSR(), Collector::CollectST(), Collector::CollectTR(), Collector::GetRadVec(), Collector::GetSpeedVec(), Collector::GetTempVec(), PromptMonth(), and Collector::SetTargetMonth().
Referenced by RunMenuLoop().
DisplayMenu()
int DisplayMenu ()
Displays the main menu and prompts the user for a selection.
Provides the user with options 1 through 5 in a menu format, and reads an integer input.
Returns
int - the option selected by the user.
Precondition
Assumes user will enter a valid integer.
Postcondition
Returns a value between 1 and 5.
Definition at line 48 of file Menu.cpp.
{
    std::cout << "1. Wind Speed Average and Standard Deviation for a Specified Month and Year\n";
    std::cout << "2. Air Temperature Average and Standard Deviation for Each Month in a Specified Year\n";
    std::cout << "3. Sample Pearson Correlation Coefficients for a Specified Month (Across All Years)\n";
    std::cout << "4. Export monthly Wind, Temperature & Solar Radiation stats for a Specified Year to WindTempSolar.csv\n";
    std::cout << "5. Exit\n";
    int choice;
    std::cout << "Option: ";
    std::cin >> choice;
    std::cout << std::endl;
    return choice;
}
Referenced by RunMenuLoop().
DisplayTempAvgAndStdDev()
void DisplayTempAvgAndStdDev (const std::map< int, AtmosLogType > & data)
Display temperature average and stddev for each month of a given year.
Iterates through all the months of a year (prompted from the user) and prints the average temperature and standard deviation values for each month, or "No Data" if month does not contain any data.
Parameters
data - An std::map containing the atmospheric data, keyed by years as integers.
Returns
void
Precondition
Assumes valid integer year.
Postcondition
Displays per-month statistics or "No Data".
Definition at line 99 of file Menu.cpp.
{
    int year = PromptYear();
    Vector<float> tempVec;
    float mean, stddev;
    std::cout << year << std::endl;
    std::map<int, AtmosLogType>::const_iterator constItr = data.find(year);
    if (constItr == data.end())
    {
        for (int month = 1; month <= 12; month++)
        {
            std::cout << MonthToString(month) << ": No Data\n";
        }
        return;
    }
    const AtmosLogType & logOfYear = constItr->second;
    for (int month = 1; month <= 12; month++)
    {
        mean = 0.0f;
        stddev = 0.0f;
        tempVec.Clear();
        GatherTempValues(logOfYear, tempVec, month);
        if (tempVec.GetSize() > 0)
        {
            mean = CalculateMean(tempVec, tempVec.GetSize());
            stddev = CalculateStandardDeviation(tempVec, tempVec.GetSize(), mean);
            std::cout << std::fixed << std::setprecision(1);
            std::cout << MonthToString(month) << ": ";
            std::cout << "average: " << mean << " degrees C, ";
            std::cout << "stddev: " << stddev << "\n";
        }
        else
        {
            std::cout << MonthToString(month) << ": No Data\n";
        }
    }
}
References PromptYear().
DisplayWindSpeedAvgAndStdDev()
void DisplayWindSpeedAvgAndStdDev (const std::map< int, AtmosLogType > & data)
Display wind speed average and standard deviation.
Prompts user for month and year, then gathers wind speed values for that time period. If data is found, calculates average and standard deviation, and displays them.
Parameters
data - An std::map containing the atmospheric data, keyed by years as integers.
Returns
void
Precondition
Assumes user inputs valid month and year.
Postcondition
Outputs statistics or "No Data" message.
Definition at line 64 of file Menu.cpp.
{
    int month = PromptMonth();
    int year = PromptYear();
    std::map<int, AtmosLogType>::const_iterator constItr = data.find(year);
    if (constItr == data.end())
    {
        std::cout << MonthToString(month) << " " << year << ": No Data\n";
        return;
    }
    const AtmosLogType & logOfYear = constItr->second;
    Vector<float> speedVec;
    GatherSpeedValues(logOfYear, speedVec, month);
    if (speedVec.GetSize() > 0)
    {
        float mean = CalculateMean(speedVec, speedVec.GetSize());
        float stddev = CalculateStandardDeviation(speedVec, speedVec.GetSize(), mean);
        std::cout << std::fixed << std::setprecision(1);
        std::cout << MonthToString(month) << " " << year << ":" << std::endl;
        std::cout << "Average Speed: " << (mean * 3.6f) << " km/h" << std::endl;
        std::cout << "Sample stddev: " << (stddev * 3.6f) << "\n";
    }
    else
    {
        std::cout << MonthToString(month) << " " << year << ": No Data\n";
    }
}
References PromptMonth(), and PromptYear().
ExportToWindTempSolarCSV()
void ExportToWindTempSolarCSV (const std::map< int, AtmosLogType > & data)
Export wind, temperature, and solar radiation data to file.
Writes formatted output of mean for speed and temperature, standard deviation for speed and temperature to WindTempSolar.csv for a given year (prompted from the user). Skips months with no data. If the year has no data at all, writes "No Data" instead.
Parameters
data - An std::map containing the atmospheric data, keyed by years as integers.
Returns
void
Precondition
Assumes data is correctly read and year input is valid.
Postcondition
Outputs a CSV file with atmosphere statistics or "No Data" in the second line.
Definition at line 177 of file Menu.cpp.
{
    int year = PromptYear();
    Vector<float> speedVec, tempVec, srVec;
    float mean, stddev, total, mad;
    bool dataPrinted = false;
    std::ofstream out("data/WindTempSolar.csv");
    if (!out)
    {
        std::cout << "Unable to open outfile\n";
        return;
    }
    out << year << std::endl;
    std::map<int, AtmosLogType>::const_iterator constItr = data.find(year);
    if (constItr == data.end())
    {
        out << "No Data\n";
        out.close();
        return;
    }
    const AtmosLogType & logOfYear = constItr->second;
    for (int month = 1; month <= 12; month++)
    {
        mean = 0.0f;
        stddev = 0.0f;
        total = 0.0f;
        mad = 0.0f;
        speedVec.Clear();
        tempVec.Clear();
        srVec.Clear();
        GatherSpeedValues(logOfYear, speedVec, month);
        GatherTempValues(logOfYear, tempVec, month);
        GatherSolarRadValues(logOfYear, srVec, month);
        if (speedVec.GetSize() > 0 || tempVec.GetSize() > 0 || srVec.GetSize() > 0)
        {
            dataPrinted = true;
            out << std::fixed << std::setprecision(1);
            out << MonthToString(month) << ",";
            if (speedVec.GetSize() > 0)
            {
                mean = CalculateMean(speedVec, speedVec.GetSize());
                stddev = CalculateStandardDeviation(speedVec, speedVec.GetSize(), mean);
                mad = MAD(speedVec, speedVec.GetSize());
                out << (mean * 3.6f) << "(" << (stddev * 3.6f) << ", " << (mad * 3.6f) << "),";
            }
            else
            {
                out << ",";
            }
            if (tempVec.GetSize() > 0)
            {
                mean = CalculateMean(tempVec, tempVec.GetSize());
                stddev = CalculateStandardDeviation(tempVec, tempVec.GetSize(), mean);
                mad = MAD(tempVec, tempVec.GetSize());
                out << mean << "(" << stddev << ", " << mad << "),";
            }
            else
            {
                out << ",";
            }
            if (srVec.GetSize() > 0)
            {
                total = CalculateTotal(srVec, srVec.GetSize());
                out << (total * (10.0f / 60.0f) / 1000.0f) << "\n";
            }
            else
            {
                out << "\n";
            }
        }
    }
    if (!dataPrinted)
    {
        out << "No Data\n";
    }
    out.close();
}
References PromptYear().
GatherSolarRadValues()
void GatherSolarRadValues (const AtmosLogType & source, Vector< float > & vec, int month)
Gathers solar radiation values for a specific year and optional month.
Gathers solar radiation values for a specific month from an atmospheric record vector. Does not gather solar radiation values below 100 W/m^2.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid solar radiation values.
Definition at line 348 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetMonth() == month && source[i].solar_rad >= 100.0f)
        {
            vec.PushBack(source[i].solar_rad);
        }
    }
}
GatherSpeedValues()
void GatherSpeedValues (const AtmosLogType & source, Vector< float > & vec, int month)
Gathers wind speed values for a specified month.
Gathers wind speed values for a specific month from an atmospheric record vector.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid speed values.
Definition at line 322 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetMonth() == month && source[i].speed != -1.0f)
        {
            vec.PushBack(source[i].speed);
        }
    }
}
GatherTempValues()
void GatherTempValues (const AtmosLogType & source, Vector< float > & vec, int month)
Gathers air temperature values for a specific month.
Gathers air temperature values for a specific month from an atmospheric record vector.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid temperature values.
Definition at line 335 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetMonth() == month && source[i].temperature != -1.0f)
        {
            vec.PushBack(source[i].temperature);
        }
    }
}
MonthToString()
const std::string & MonthToString (int monthNum) static
Definition at line 305 of file Menu.cpp.
{
    static const std::string invalid = "Invalid Month";
    static const std::string months[12] = {"January", "February", "March", "April", "May", "June",
                                           "July", "August", "September", "October", "November", "December"};
    if (monthNum >= 1 && monthNum <= 12)
    {
        return months[monthNum - 1];
    }
    else
    {
        return invalid;
    }
}
PrintDateAndTime()
void PrintDateAndTime (const AtmosRecType & a)
Prints the date and time from a given AtmosRecType record.
Outputs the formatted date (DD/MM/YYYY) and time (HH:MM) to the console.
Parameters
a - The atmospheric record vector containing date and time information.
Precondition
a must contain valid Date and Time objects.
Postcondition
The date and time are printed to the console.
Definition at line 269 of file Menu.cpp.
{
    std::cout << a.date.GetDay() << "/" << a.date.GetMonth() << "/" << a.date.GetYear() << " "
              << a.time.GetHour() << ":" << a.time.GetMinute() << std::endl;
}
PromptMonth()
int PromptMonth ()
Prompts the user to enter a valid month (1-12).
Prompts the user to enter a valid month (1-12). Loops until a valid month is entered.
Returns
int - A valid month (1 through 12).
Precondition
Function is called in a valid context, ie. in main() or any other function.
Postcondition
Returns a valid month between 1 and 12.
Definition at line 277 of file Menu.cpp.
{
    int m = -1;
    do
    {
        std::cout << "Enter the month (1-12): ";
        std::cin >> m;
    }
    while (m <= 0 || m > 12);
    return m;
}
Referenced by CalculateAndDisplaySPCC(), and DisplayWindSpeedAvgAndStdDev().
PromptYear()
int PromptYear ()
Prompts the user to enter a year.
Prompts the user to enter a year. Accepts any integer as valid input.
Returns
int - The entered year.
Precondition
Function is called in a valid context, ie. in main() or any other function.
Postcondition
Returns an integer value representing the year.
Definition at line 293 of file Menu.cpp.
{
    int y;
    std::cout << "Enter the year: ";
    std::cin >> y;
    return y;
}
Referenced by DisplayTempAvgAndStdDev(), DisplayWindSpeedAvgAndStdDev(), and ExportToWindTempSolarCSV().
RunMenuLoop()
void RunMenuLoop (const BST< AtmosRecType > & atmos_bst, const std::map< int, AtmosLogType > & atmos_map)
Runs the menu loop and processes the user's choice.
Handles the menu loop after displaying the menu, and runs the method associated with the user's menu choice.
Parameters
atmos_bst - A BST containing the atmospheric data.
atmos_map - An std::map containing the atmospheric data, keyed by years as integers.
Returns
void
Precondition
Assumes user will enter a valid integer.
Postcondition
Calls the method associated with the menu choice.
Definition at line 16 of file Menu.cpp.
{
    int choice = DisplayMenu();
    while(choice != 5)
    {
        switch(choice)
        {
        case 1:
            DisplayWindSpeedAvgAndStdDev(atmos_map);
            std::cout << std::endl;
            break;
        case 2:
            DisplayTempAvgAndStdDev(atmos_map);
            std::cout << std::endl;
            break;
        case 3:
            CalculateAndDisplaySPCC(atmos_bst);
            std::cout << std::endl;
            break;
        case 4:
            ExportToWindTempSolarCSV(atmos_map);
            std::cout << std::endl;
            break;
        default:
            std::cout << "Invalid option\n";
        }
        choice = DisplayMenu();
    }
}
References CalculateAndDisplaySPCC(), and DisplayMenu().