Atmosphere: Menu.h File Reference
Menu.h File Reference
#include "atmospherelogtypes.h"
#include <string>
Functions
int DisplayMenu ()
Displays the main menu and prompts the user for a selection.
void OptionOne (const AtmosLogType &a)
Handles Option 1: Display wind speed average and standard deviation.
void OptionTwo (const AtmosLogType &a)
Handles Option 2: Display temperature average and stddev for each month of a given year.
void OptionThree (const AtmosLogType &a)
Handles Option 3: Display total solar radiation for each month of a given year.
void OptionFour (const AtmosLogType &a)
Handles Option 4: Export wind, temperature, and solar radiation data to file.
void PrintDateAndTime (const AtmosRecType &a)
Prints the date and time from a given AtmosRecType record.
int PromptMonth ()
Prompts the user to enter a valid month (1-12).
int PromptYear ()
Prompts the user to enter a year.
static const std::string & MonthToString (int monthNum)
Converts a month number to its string representation.
void GatherSpeedValues (const AtmosLogType &source, Vector< float > &vec, int year, int month)
Gathers wind speed values for a specific year and optional month.
void GatherTempValues (const AtmosLogType &source, Vector< float > &vec, int year, int month)
Gathers air temperature values for a specific year and optional month.
void GatherSolarRadValues (const AtmosLogType &source, Vector< float > &vec, int year, int month)
Gathers solar radiation values for a specific year and optional month.
Function Documentation
DisplayMenu()
int DisplayMenu ()
Displays the main menu and prompts the user for a selection.
Provides the user with options 1 through 5 in a menu format, and reads an integer input.
Returns
int - the option selected by the user.
Precondition
Assumes user will enter a valid integer.
Postcondition
Returns a value between 1 and 5.
Definition at line 12 of file Menu.cpp.
{
    std::cout << "1. Wind Speed Average and Standard Deviation for a Specified Month and Year\n";
    std::cout << "2. Air Temperature Average and Standard Deviation for Each Month in a Specified Year\n";
    std::cout << "3. Total Solar Radiation (in kWh/m^2) for Each Month in a Specified Year\n";
    std::cout << "4. Export monthly Wind, Temperature & Solar Radiation stats for a Specified Year to WindTempSolar.csv\n";
    std::cout << "5. Exit\n";
    int choice;
    std::cout << "Option: ";
    std::cin >> choice;
    std::cout << std::endl;
    return choice;
}
Referenced by main().
GatherSolarRadValues()
void GatherSolarRadValues (const AtmosLogType & source, Vector< float > & vec, int year, int month)
Gathers solar radiation values for a specific year and optional month.
Gathers solar radiation values for a specific year and optional month from an atmospheric record vector. Does not gather solar radiation values below 100 W/m^2.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
year - The year to filter data.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid solar radiation values.
Definition at line 285 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetYear() == year
            && (month == 0 || source[i].date.GetMonth() == month)
            && source[i].solar_rad >= 100.0f)
        {
            vec.PushBack(source[i].solar_rad);
        }
    }
}
GatherSpeedValues()
void GatherSpeedValues (const AtmosLogType & source, Vector< float > & vec, int year, int month)
Gathers wind speed values for a specific year and optional month.
Gathers wind speed values for a specific year and optional month from an atmospheric record vector.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
year - The year to filter data.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid speed values.
Definition at line 255 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetYear() == year
            && (month == 0 || source[i].date.GetMonth() == month)
            && source[i].speed != -1.0f)
        {
            vec.PushBack(source[i].speed);
        }
    }
}
GatherTempValues()
void GatherTempValues (const AtmosLogType & source, Vector< float > & vec, int year, int month)
Gathers air temperature values for a specific year and optional month.
Gathers air temperature values for a specific year and optional month from an atmospheric record vector.
Parameters
source - Const Reference to Atmospheric record vector.
vec - Reference to Vector to store speed values.
year - The year to filter data.
month - The month to filter data.
Precondition
source must contain valid atmospheric records.
Postcondition
vec will be populated with valid temperature values.
Definition at line 270 of file Menu.cpp.
{
    for (int i = 0; i < source.GetSize(); i++)
    {
        if (source[i].date.GetYear() == year
            && (month == 0 || source[i].date.GetMonth() == month)
            && source[i].temperature != -1.0f)
        {
            vec.PushBack(source[i].temperature);
        }
    }
}
MonthToString()
const std::string & MonthToString (int monthNum) static
Converts a month number to its string representation.
Converts a month number to its string representation.
Parameters
monthNum - The month number (1-12).
Returns
const std::string& - Name of the month or "Invalid Month" if out of range as a static const string reference.
Precondition
monthNum is an integer.
Postcondition
Returns corresponding month string or "Invalid Month" as a static const string reference.
OptionFour()
void OptionFour (const AtmosLogType & a)
Handles Option 4: Export wind, temperature, and solar radiation data to file.
Writes formatted output of mean for speed and temperature, standard deviation for speed and temperature to WindTempSolar.csv for a given year (prompted from the user). Skips months with no data. If the year has no data at all, writes "No Data" instead.
Parameters
a - The atmospheric data record vector.
Returns
void
Precondition
Assumes data is correctly read and year input is valid.
Postcondition
Outputs a CSV file with atmosphere statistics or "No Data" in the second line.
Definition at line 122 of file Menu.cpp.
{
    int year = PromptYear();
    Vector<float> speedVec, tempVec, srVec;
    float mean, stddev, total;
    bool dataPrinted = false;
    std::ofstream out("data/WindTempSolar.csv");
    if (!out)
    {
        std::cout << "Unable to open outfile\n";
        return;
    }
    out << year << std::endl;
    for (int month = 1; month <= 12; month++)
    {
        mean = 0.0f;
        stddev = 0.0f;
        total = 0.0f;
        speedVec.Clear();
        tempVec.Clear();
        srVec.Clear();
        GatherSpeedValues(a, speedVec, year, month);
        GatherTempValues(a, tempVec, year, month);
        GatherSolarRadValues(a, srVec, year, month);
        if (speedVec.GetSize() > 0 || tempVec.GetSize() > 0 || srVec.GetSize() > 0)
        {
            dataPrinted = true;
            out << std::fixed << std::setprecision(1);
            out << MonthToString(month) << ",";
            if (speedVec.GetSize() > 0)
            {
                mean = CalculateMean(speedVec, speedVec.GetSize());
                stddev = CalculateStandardDeviation(speedVec, speedVec.GetSize(), mean);
                out << (mean * 3.6f) << "(" << stddev << "),";
            }
            else
            {
                out << ",";
            }
            if (tempVec.GetSize() > 0)
            {
                mean = CalculateMean(tempVec, tempVec.GetSize());
                stddev = CalculateStandardDeviation(tempVec, tempVec.GetSize(), mean);
                out << mean << "(" << stddev << "),";
            }
            else
            {
                out << ",";
            }
            if (srVec.GetSize() > 0)
            {
                total = CalculateTotal(srVec, srVec.GetSize());
                out << (total * (10.0f / 60.0f) / 1000.0f) << "\n";
            }
            else
            {
                out << "\n";
            }
        }
    }
    if (!dataPrinted)
    {
        out << "No Data\n";
    }
    out.close();
}
References PromptYear().
OptionOne()
void OptionOne (const AtmosLogType & a)
Handles Option 1: Display wind speed average and standard deviation.
Prompts user for month and year, then gathers wind speed values for that time period. If data is found, calculates average and standard deviation, and displays them.
Parameters
a - The atmospheric data record vector.
Returns
void
Precondition
Assumes user inputs valid month and year.
Postcondition
Outputs statistics or "No Data" message.
Definition at line 28 of file Menu.cpp.
{
    int month = PromptMonth();
    int year = PromptYear();
    Vector<float> speedVec;
    GatherSpeedValues(a, speedVec, year, month);
    if (speedVec.GetSize() > 0)
    {
        float mean = CalculateMean(speedVec, speedVec.GetSize());
        float stddev = CalculateStandardDeviation(speedVec, speedVec.GetSize(), mean);
        std::cout << std::fixed << std::setprecision(1);
        std::cout << MonthToString(month) << " " << year << ":" << std::endl;
        std::cout << "Average Speed: " << (mean * 3.6f) << " km/h" << std::endl;
        std::cout << "Sample stddev: " << stddev << "\n";
    }
    else
    {
        std::cout << MonthToString(month) << " " << year << ": No Data\n";
    }
}
References PromptMonth(), and PromptYear().
OptionThree()
void OptionThree (const AtmosLogType & a)
Handles Option 3: Display total solar radiation for each month of a given year.
Prints monthly solar radiation totals in kWh/m^2 for a given year (prompted from the user), or "No Data" if month does not contain any data.
Parameters
a - The atmospheric data record vector.
Returns
void
Precondition
Assumes user inputs a valid year.
Postcondition
Displays total solar radiation per month or "No Data".
Definition at line 90 of file Menu.cpp.
{
    int year = PromptYear();
    Vector<float> srVec;
    float total;
    std::cout << year << std::endl;
    for (int month = 1; month <= 12; month++)
    {
        total = 0.0f;
        srVec.Clear();
        GatherSolarRadValues(a, srVec, year, month);
        if (srVec.GetSize() > 0)
        {
            total = CalculateTotal(srVec, srVec.GetSize());
            std::cout << std::fixed << std::setprecision(1);
            std::cout << MonthToString(month) << ": " << (total * (10.0f / 60.0f) / 1000.0f) << " kWh/m^2\n";
        }
        else
        {
            std::cout << MonthToString(month) << ": No Data\n";
        }
    }
}
References PromptYear().
OptionTwo()
void OptionTwo (const AtmosLogType & a)
Handles Option 2: Display temperature average and stddev for each month of a given year.
Iterates through all the months of a year (prompted from the user) and prints the average temperature and standard deviation values for each month, or "No Data" if month does not contain any data.
Parameters
a - The atmospheric data record vector.
Returns
void
Precondition
Assumes valid integer year.
Postcondition
Displays per-month statistics or "No Data".
Definition at line 54 of file Menu.cpp.
{
    int year = PromptYear();
    Vector<float> tempVec;
    float mean, stddev;
    std::cout << year << std::endl;
    for (int month = 1; month <= 12; month++)
    {
        mean = 0.0f;
        stddev = 0.0f;
        tempVec.Clear();
        GatherTempValues(a, tempVec, year, month);
        if (tempVec.GetSize() > 0)
        {
            mean = CalculateMean(tempVec, tempVec.GetSize());
            stddev = CalculateStandardDeviation(tempVec, tempVec.GetSize(), mean);
            std::cout << std::fixed << std::setprecision(1);
            std::cout << MonthToString(month) << ": ";
            std::cout << "average: " << mean << " degrees C, ";
            std::cout << "stddev: " << stddev << "\n";
        }
        else
        {
            std::cout << MonthToString(month) << ": No Data\n";
        }
    }
}
References PromptYear().
PrintDateAndTime()
void PrintDateAndTime (const AtmosRecType & a)
Prints the date and time from a given AtmosRecType record.
Outputs the formatted date (DD/MM/YYYY) and time (HH:MM) to the console.
Parameters
a - The atmospheric record vector containing date and time information.
Precondition
a must contain valid Date and Time objects.
Postcondition
The date and time are printed to the console.
Definition at line 202 of file Menu.cpp.
{
    std::cout << a.date.GetDay() << "/" << a.date.GetMonth() << "/" << a.date.GetYear() << " "
              << a.time.GetHour() << ":" << a.time.GetMinute() << std::endl;
}
PromptMonth()
int PromptMonth ()
Prompts the user to enter a valid month (1-12).
Prompts the user to enter a valid month (1-12). Loops until a valid month is entered.
Returns
int - A valid month (1 through 12).
Precondition
Function is called in a valid context, ie. in main() or any other function.
Postcondition
Returns a valid month between 1 and 12.
Definition at line 210 of file Menu.cpp.
{
    int m = -1;
    do
    {
        std::cout << "Enter the month (1-12): ";
        std::cin >> m;
    }
    while (m <= 0 || m > 12);
    return m;
}
Referenced by OptionOne().
PromptYear()
int PromptYear ()
Prompts the user to enter a year.
Prompts the user to enter a year. Accepts any integer as valid input.
Returns
int - The entered year.
Precondition
Function is called in a valid context, ie. in main() or any other function.
Postcondition
Returns an integer value representing the year.
Definition at line 226 of file Menu.cpp.
{
    int y;
    std::cout << "Enter the year: ";
    std::cin >> y;
    return y;
}
Referenced by OptionFour(), OptionOne(), OptionThree(), and OptionTwo().