Atmosphere-ICT283: Utils.cpp File Reference
Utils.cpp File Reference
#include "utils.h"
#include "date.h"
#include "mytime.h"
#include "VectorTest/unit.h"
#include <iostream>
#include <string>
Functions
std::ostream & operator<< (std::ostream &os, const Date &D)
Overloads the output operator for a Date object.
bool operator< (const Date &lhs, const Date &rhs)
Less-than operator for comparing two Date objects.
bool operator> (const Date &lhs, const Date &rhs)
Greater-than operator for comparing two Date objects.
bool operator== (const Date &lhs, const Date &rhs)
Comparison operator for comparing two Date objects.
bool operator< (const MyTime &lhs, const MyTime &rhs)
Less-than operator for comparing two MyTime objects.
bool operator> (const MyTime &lhs, const MyTime &rhs)
Greater-than operator for comparing two MyTime objects.
bool operator== (const MyTime &lhs, const MyTime &rhs)
Comparison operator for comparing two MyTime objects.
std::istream & operator>> (std::istream &input, Unit &U)
Overloads the input operator for a Unit object.
std::ostream & operator<< (std::ostream &os, const Unit &U)
Overloads the output operator for a Unit object.
Function Documentation
operator<() [1/2]
bool operator< (const Date & lhs, const Date & rhs)
Less-than operator for comparing two Date objects.
Compares two Date objects chronologically, first by year, then by month, and finally by day.
Parameters
lhs - The left-hand side Date object.
rhs - The right-hand side Date object.
Returns
True if lhs is earlier than rhs; otherwise, false.
Precondition
Both Date objects must be properly initialized with valid year, month, and day.
Postcondition
No change is made to either Date object.
Definition at line 18 of file Utils.cpp.
{
    if (lhs.GetYear() != rhs.GetYear())
    {
        return lhs.GetYear() < rhs.GetYear();
    }
    if (lhs.GetMonth() != rhs.GetMonth())
    {
        return lhs.GetMonth() < rhs.GetMonth();
    }
    return lhs.GetDay() < rhs.GetDay();
}
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
Referenced by operator<().
operator<() [2/2]
bool operator< (const MyTime & lhs, const MyTime & rhs)
Less-than operator for comparing two MyTime objects.
Compares two MyTime objects chronologically, first by hour, then by minute.
Parameters
lhs - The left-hand side MyTime object.
rhs - The right-hand side MyTime object.
Returns
True if lhs is earlier than rhs; otherwise, false.
Precondition
Both MyTime objects must be properly initialized with valid hour and minute.
Postcondition
No change is made to either MyTime object.
Definition at line 61 of file Utils.cpp.
{
    if (lhs.GetHour() != rhs.GetHour())
    {
        return lhs.GetHour() < rhs.GetHour();
    }
    return lhs.GetMinute() < rhs.GetMinute();
}
References MyTime::GetHour(), and MyTime::GetMinute().
Referenced by operator<().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const Date & D)
Overloads the output operator for a Date object.
The method overloads the output operator, assigning the Date formatted as "DD/MM/YYYY" to the output stream and returning it.
Parameters
os - the output stream passed as a reference.
D - the reference to the Date object.
Returns
the output stream containing the formatted date.
Precondition
Date must be a valid, constructed object.
Postcondition
Output stream contains date in the format DD/MM/YYYY.
Definition at line 10 of file Utils.cpp.
{
    os << D.GetDay() << "/" << D.GetMonth() << "/" << D.GetYear();
    return os;
}
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const Unit & U)
Overloads the output operator for a Unit object.
The method overloads the output operator, assigning the Unit formatted as "ID Name Credits" to the output stream and returning it.
Parameters
os - the output stream passed as a reference.
U - the reference to the Unit object.
Returns
the output stream containing the formatted date.
Precondition
Unit must be a valid, constructed object.
Postcondition
Output stream contains date in the format "ID Name Credits".
Definition at line 112 of file Utils.cpp.
{
    os << U.GetId() << " " << U.GetName() << " " << U.GetCredits();
    return os;
}
operator==() [1/2]
bool operator== (const Date & lhs, const Date & rhs)
Comparison operator for comparing two Date objects.
Checks if two Date objects represent the same calendar date, comparing year, month, and day.
Parameters
lhs - The left-hand side Date object.
rhs - The right-hand side Date object.
Returns
True if both Date objects have the same year, month, and day; otherwise, false.
Precondition
Both Date objects must be properly initialized with valid values.
Postcondition
No change is made to either Date object.
Definition at line 52 of file Utils.cpp.
{
    return lhs.GetYear() == rhs.GetYear() &&
           lhs.GetMonth() == rhs.GetMonth() &&
           lhs.GetDay() == rhs.GetDay();
}
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
Referenced by operator<(), operator==(), and operator>().
operator==() [2/2]
bool operator== (const MyTime & lhs, const MyTime & rhs)
Comparison operator for comparing two MyTime objects.
Checks if two MyTime objects represent the same times, comparing hour and minute.
Parameters
lhs - The left-hand side MyTime object.
rhs - The right-hand side MyTime object.
Returns
True if both MyTime objects have the same hour and minute; otherwise, false.
Precondition
Both MyTime objects must be properly initialized with valid values.
Postcondition
No change is made to either MyTime object.
Definition at line 85 of file Utils.cpp.
{
    return lhs.GetHour() == rhs.GetHour() &&
           lhs.GetMinute() == rhs.GetMinute();
}
References MyTime::GetHour(), and MyTime::GetMinute().
Referenced by operator<(), operator==(), and operator>().
operator>() [1/2]
bool operator> (const Date & lhs, const Date & rhs)
Greater-than operator for comparing two Date objects.
Compares two Date objects chronologically, first by year, then by month, and finally by day.
Parameters
lhs - The left-hand side Date object.
rhs - The right-hand side Date object.
Returns
True if lhs is later than rhs; otherwise, false.
Precondition
Both Date objects must be properly initialized with valid year, month, and day.
Postcondition
No change is made to either Date object.
Definition at line 35 of file Utils.cpp.
{
    if (lhs.GetYear() != rhs.GetYear())
    {
        return lhs.GetYear() > rhs.GetYear();
    }
    if (lhs.GetMonth() != rhs.GetMonth())
    {
        return lhs.GetMonth() > rhs.GetMonth();
    }
    return lhs.GetDay() > rhs.GetDay();
}
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
Referenced by operator>().
operator>() [2/2]
bool operator> (const MyTime & lhs, const MyTime & rhs)
Greater-than operator for comparing two MyTime objects.
Compares two MyTime objects chronologically, first by hour, then by minute.
Parameters
lhs - The left-hand side MyTime object.
rhs - The right-hand side MyTime object.
Returns
True if lhs is later than rhs; otherwise, false.
Precondition
Both MyTime objects must be properly initialized with valid hour and minute.
Postcondition
No change is made to either MyTime object.
Definition at line 73 of file Utils.cpp.
{
    if (lhs.GetHour() != rhs.GetHour())
    {
        return lhs.GetHour() > rhs.GetHour();
    }
    return lhs.GetMinute() >  rhs.GetMinute();
}
References MyTime::GetHour(), and MyTime::GetMinute().
Referenced by operator>().
operator>>()
std::istream & operator>> (std::istream & input, Unit & U)
Overloads the input operator for a Unit object.
This method overloads the input operator, reading each line of the input stream as a string, and parsing the Unit ID, Name, and Credits and assigning their values to the passed Unit object.
Parameters
input - the input stream as a reference.
U - the reference to the Unit object.
Returns
the input stream reference after the data has been extracted.
Precondition
The input stream must be formatted with comma separated values (e.g. "ID,Name,Credits"), and the value of Credits must be a valid number data type.
Postcondition
The relevant Unit data will be extracted from the input stream and stored in the passed Unit object, and the input stream will be advanced passed the consumed data.
Definition at line 93 of file Utils.cpp.
{
    std::string name, id;
    int credits;
    std::getline(input, id, ',');
    U.SetId(id);
    std::getline(input, name, ',');
    U.SetName(name);
    input >> credits;
    U.SetCredits(credits);
    return input;
}