Atmosphere-ICT283: MyTime Class Reference
MyTime Class Reference
Stores and manages 24-hour time using hour and minute.
#include <MyTime.h>
Public Member Functions
MyTime ()
Construct a time object.
MyTime (int hour, int minute)
Construct a time object using the passed parameters.
void SetHour (int hour)
Sets the value of the hour variable.
int GetHour () const
Returns the value of the hour variable as an integer.
void SetMinute (int minute)
Sets the value of the minute variable.
int GetMinute () const
Returns the value of the minute variable as an integer.
Private Attributes
int m_hour
int m_minute
the hour as a two-digit number in 24 hour format
Detailed Description
Stores and manages 24-hour time using hour and minute.
This class represents a time value consisting of an hour and minute, using 24-hour format. It allows for setting and retrieving time values.
Author
Nabeel
Version
01
Date
14/06/2025 Nabeel, Started
Todo
Nothing
Bug
No bugs so far
Definition at line 22 of file MyTime.h.
Constructor & Destructor Documentation
MyTime() [1/2]
MyTime::MyTime ()
Construct a time object.
This constructor will construct a new object with hour and minute set to 0.
Precondition
new object is initialized.
Postcondition
a time object is created with hour and minute set to 0.
Definition at line 5 of file MyTime.cpp.
{
    m_hour = 0;
    m_minute = 0;
}
References m_hour, and m_minute.
MyTime() [2/2]
MyTime::MyTime (int hour, int minute)
Construct a time object using the passed parameters.
This constructor will overload the default constructor, passing values for the hour and minute to be assigned to the respective private variables, to create a new time object.
Parameters
hour - two-digit number for hour (in 24 hour format).
minute - two-digit number for minute
Precondition
hour and minute are valid non-zero integers.
Postcondition
a date object is created with m_hour = hour and m_minute = minute.
Definition at line 13 of file MyTime.cpp.
{
    m_hour = hour;
    m_minute = minute;
}
References m_hour, and m_minute.
Member Function Documentation
GetHour()
int MyTime::GetHour () const
Returns the value of the hour variable as an integer.
Retrieves the current value of the hour member variable as an integer.
Returns
The hour (in 24 hour format).
Precondition
The time object must be fully constructed and initialized.
Postcondition
The object remains unchanged; the returned value reflects the current hour.
Definition at line 28 of file MyTime.cpp.
{
    return m_hour;
}
References m_hour.
Referenced by operator<(), operator==(), and operator>().
GetMinute()
int MyTime::GetMinute () const
Returns the value of the minute variable as an integer.
Retrieves the current value of the minute member variable as an integer.
Returns
The minute.
Precondition
The time object must be fully constructed and initialized.
Postcondition
The object remains unchanged; the returned value reflects the current minute.
Definition at line 42 of file MyTime.cpp.
{
    return m_minute;
}
References m_minute.
Referenced by operator<(), operator==(), and operator>().
SetHour()
void MyTime::SetHour (int hour)
Sets the value of the hour variable.
Updates the hour member variable to the specified value.
Parameters
hour The new value of hour as an integer (in 24 hour format).
Returns
void
Precondition
The date object must be fully constructed and initialized.
Postcondition
The m_minute variable is updated to the value of the passed parameter hour.
Definition at line 21 of file MyTime.cpp.
{
    m_hour = hour;
}
References m_hour.
Referenced by ParseTimeRecord().
SetMinute()
void MyTime::SetMinute (int minute)
Sets the value of the minute variable.
Updates the minute member variable to the specified value.
Parameters
minute The new value of minute as an integer.
Returns
void
Precondition
The date object must be fully constructed and initialized.
Postcondition
The m_minute variable is updated to the value of the passed parameter minute.
Definition at line 35 of file MyTime.cpp.
{
    m_minute = minute;
}
References m_minute.
Referenced by ParseTimeRecord().
Member Data Documentation
m_hour
int MyTime::m_hour private
Definition at line 94 of file MyTime.h.
Referenced by GetHour(), MyTime(), MyTime(), and SetHour().
m_minute
int MyTime::m_minute private
the hour as a two-digit number in 24 hour format
Definition at line 95 of file MyTime.h.
Referenced by GetMinute(), MyTime(), MyTime(), and SetMinute().
The documentation for this class was generated from the following files:
MyTime.h
MyTime.cpp