Atmosphere-ICT283: Collector Class Reference
Collector Class Reference
A static utility class for collecting and storing atmospheric data measurements by month.
#include <Collector.h>
Static Public Member Functions
static void Clear ()
Clears all stored data and resets the target month.
static void SetTargetMonth (int month)
Sets the month used as a filter for data collection.
static int GetTargetMonth ()
Retrieves the current target month.
static Vector< float > & GetSpeedVec ()
Returns the vector containing collected wind speed values.
static Vector< float > & GetTempVec ()
Returns the vector containing collected temperature values.
static Vector< float > & GetRadVec ()
Returns the vector containing collected solar radiation values.
static void CollectST (const AtmosRecType &a)
Collects wind speed and temperature data for the target month.
static void CollectSR (const AtmosRecType &a)
Collects wind speed and solar radiation data for the target month.
static void CollectTR (const AtmosRecType &a)
Collects temperature and solar radiation data for the target month.
Static Private Attributes
static Vector< float > m_sVec
static Vector< float > m_tVec
Vector for Wind Speeds.
static Vector< float > m_rVec
Vector for Air Temperatures.
static int m_targetMonth = 0
Vector for Solar Radiation.
Detailed Description
A static utility class for collecting and storing atmospheric data measurements by month.
The Collector class provides a centralized mechanism for gathering atmospheric measurements (wind speed, air temperature, and solar radiation) from AtmosRecType records. It maintains three static vectors to store the collected data and allows filtering by a target month. The class offers separate collection methods for different measurement combinations and provides access to the stored data vectors.
Author
Nabeel
Version
01
Date
22/07/2025 Nabeel, Started
Todo
Nothing
Bug
No bugs so far
Definition at line 29 of file Collector.h.
Member Function Documentation
Clear()
void Collector::Clear () static
Clears all stored data and resets the target month.
Empties the vectors holding wind speed, temperature, and solar radiation values, and resets the target month to 0.
Returns
void
Precondition
None.
Postcondition
All vectors are cleared and m_targetMonth is reset to 0.
Definition at line 14 of file Collector.cpp.
{
    m_sVec.Clear();
    m_tVec.Clear();
    m_rVec.Clear();
    m_targetMonth = 0;
}
References m_targetMonth.
Referenced by CalculateAndDisplaySPCC().
CollectSR()
void Collector::CollectSR (const AtmosRecType & a) static
Collects wind speed and solar radiation data for the target month.
Extracts and stores valid wind speed and solar radiation values from the provided record if the record's month matches the target month and solar radiation is ≥ 100.0.
Parameters
a The AtmosRecType record to extract data from.
Precondition
m_targetMonth must be set; a must be valid.
Postcondition
If conditions are met, data is appended to m_sVec and m_rVec.
Definition at line 74 of file Collector.cpp.
{
    if (a.date.GetMonth() != m_targetMonth)
    {
        return;
    }
    if ((a.speed != -1.0f) && (a.solar_rad >= 100.0f))
    {
        m_sVec.PushBack(a.speed);
        m_rVec.PushBack(a.solar_rad);
    }
}
References AtmosRecType::date, Date::GetMonth(), m_targetMonth, AtmosRecType::solar_rad, and AtmosRecType::speed.
Referenced by CalculateAndDisplaySPCC().
CollectST()
void Collector::CollectST (const AtmosRecType & a) static
Collects wind speed and temperature data for the target month.
Extracts and stores valid wind speed and temperature values from the provided record if the record's month matches the target month.
Parameters
a The AtmosRecType record to extract data from.
Precondition
m_targetMonth must be set; a must be valid.
Postcondition
If conditions are met, data is appended to m_sVec and m_tVec.
Definition at line 59 of file Collector.cpp.
{
    if (a.date.GetMonth() != m_targetMonth)
    {
        return;
    }
    if ((a.speed != -1.0f) && (a.temperature != -1.0f))
    {
        m_sVec.PushBack(a.speed);
        m_tVec.PushBack(a.temperature);
    }
}
References AtmosRecType::date, Date::GetMonth(), m_targetMonth, AtmosRecType::speed, and AtmosRecType::temperature.
Referenced by CalculateAndDisplaySPCC().
CollectTR()
void Collector::CollectTR (const AtmosRecType & a) static
Collects temperature and solar radiation data for the target month.
Extracts and stores valid temperature and solar radiation values from the provided record if the record's month matches the target month and solar radiation is ≥ 100.0.
Parameters
a The AtmosRecType record to extract data from.
Precondition
m_targetMonth must be set; a must be valid.
Postcondition
If conditions are met, data is appended to m_tVec and m_rVec.
Definition at line 89 of file Collector.cpp.
{
    if (a.date.GetMonth() != m_targetMonth)
    {
        return;
    }
    if ((a.temperature != -1.0f) && (a.solar_rad >= 100.0f))
    {
        m_tVec.PushBack(a.temperature);
        m_rVec.PushBack(a.solar_rad);
    }
}
References AtmosRecType::date, Date::GetMonth(), m_targetMonth, AtmosRecType::solar_rad, and AtmosRecType::temperature.
Referenced by CalculateAndDisplaySPCC().
GetRadVec()
Vector< float > & Collector::GetRadVec () static
Returns the vector containing collected solar radiation values.
Returns
Reference to the vector storing solar radiation measurements.
Precondition
Clear() should have been called before data collection starts.
Postcondition
No changes to internal state.
Definition at line 52 of file Collector.cpp.
{
    return m_rVec;
}
Referenced by CalculateAndDisplaySPCC().
GetSpeedVec()
Vector< float > & Collector::GetSpeedVec () static
Returns the vector containing collected wind speed values.
Returns
Reference to the vector storing wind speed measurements.
Precondition
Clear() should have been called before data collection starts.
Postcondition
No changes to internal state.
Definition at line 38 of file Collector.cpp.
{
    return m_sVec;
}
Referenced by CalculateAndDisplaySPCC().
GetTargetMonth()
int Collector::GetTargetMonth () static
Retrieves the current target month.
Returns
Integer value of the currently set target month.
Precondition
m_targetMonth must have been set via SetTargetMonth().
Postcondition
No changes to internal state.
Definition at line 31 of file Collector.cpp.
{
    return m_targetMonth;
}
References m_targetMonth.
GetTempVec()
Vector< float > & Collector::GetTempVec () static
Returns the vector containing collected temperature values.
Returns
Reference to the vector storing temperature measurements.
Precondition
Clear() should have been called before data collection starts.
Postcondition
No changes to internal state.
Definition at line 45 of file Collector.cpp.
{
    return m_tVec;
}
Referenced by CalculateAndDisplaySPCC().
SetTargetMonth()
void Collector::SetTargetMonth (int month) static
Sets the month used as a filter for data collection.
Parameters
month Integer representing the target month (1-12).
Returns
void
Precondition
1 <= month <= 12.
Postcondition
m_targetMonth is updated to the provided value.
Definition at line 24 of file Collector.cpp.
{
    m_targetMonth = month;
}
References m_targetMonth.
Referenced by CalculateAndDisplaySPCC().
Member Data Documentation
m_rVec
Vector< float > Collector::m_rVec static private
Vector for Air Temperatures.
Definition at line 128 of file Collector.h.
m_sVec
Vector< float > Collector::m_sVec static private
Definition at line 126 of file Collector.h.
m_targetMonth
int Collector::m_targetMonth = 0 static private
Vector for Solar Radiation.
Definition at line 129 of file Collector.h.
Referenced by Clear(), CollectSR(), CollectST(), CollectTR(), GetTargetMonth(), and SetTargetMonth().
m_tVec
Vector< float > Collector::m_tVec static private
Vector for Wind Speeds.
Definition at line 127 of file Collector.h.
The documentation for this class was generated from the following files:
Collector.h
Collector.cpp