Atmosphere-ICT283: Date Class Reference
Date Class Reference
Represents a calendar date using integers that represent when marks were obtained for a unit.
#include <Date.h>
Public Member Functions
Date ()
Construct a date object.
Date (int day, int month, int year)
Construct a date object using the passed parameters.
int GetDay () const
Returns the value of the day variable as an integer.
void SetDay (int day)
Sets the value of the day variable.
int GetMonth () const
Returns the value of the month variable as an integer.
void SetMonth (int month)
Sets the value of the month variable.
int GetYear () const
Returns the value of the year variable as an integer.
void SetYear (int year)
Sets the value of the year variable.
Private Attributes
int m_day
int m_month
The day of the month as a number.
int m_year
The month as a number.
Detailed Description
Represents a calendar date using integers that represent when marks were obtained for a unit.
The Date class stores a date as three integer values: day, month, and year. It provides getter and setter functions for each field.
Author
Nabeel
Version
01
Date
1/06/2025 Nabeel, Started
Todo
Nothing
Bug
No bugs so far
Definition at line 22 of file Date.h.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
Construct a date object.
This constructor will construct a new object with day, month, and year set to 0.
Precondition
new object is initialized.
Postcondition
a date object is created with day, month, and year set to 0.
Definition at line 5 of file Date.cpp.
{
    m_day = 1;
    m_month = 1;
    m_year = 1;
}
References m_day, m_month, and m_year.
Date() [2/2]
Date::Date (int day, int month, int year)
Construct a date object using the passed parameters.
This constructor will overload the default constructor, passing values for the day, month and year to be assigned to the respective private variables, to create a new date object.
Parameters
day - day of the month as a number.
month - month as a double digit number.
year - the year as a four digit number.
Precondition
day, month and year are valid non-zero integers.
Postcondition
a date object is created with m_day = day, m_month = month, and m_year = year.
Definition at line 14 of file Date.cpp.
{
    m_day = day;
    m_month = month;
    m_year = year;
}
References m_day, m_month, and m_year.
Member Function Documentation
GetDay()
int Date::GetDay () const
Returns the value of the day variable as an integer.
Retrieves the current value of the day member variable as an integer.
Returns
The day of the month.
Precondition
The date object must be fully constructed and initialized.
Postcondition
The object remains unchanged; the returned value reflects the current day.
Definition at line 23 of file Date.cpp.
{
    return m_day;
}
References m_day.
Referenced by operator<(), operator<<(), operator==(), and operator>().
GetMonth()
int Date::GetMonth () const
Returns the value of the month variable as an integer.
Retrieves the current value of the month member variable as an integer.
Returns
The month.
Precondition
The date object must be fully constructed and initialized.
Postcondition
The object remains unchanged; the returned value reflects the current month.
Definition at line 37 of file Date.cpp.
{
    return m_month;
}
References m_month.
Referenced by Collector::CollectSR(), Collector::CollectST(), Collector::CollectTR(), operator<(), operator<<(), operator==(), and operator>().
GetYear()
int Date::GetYear () const
Returns the value of the year variable as an integer.
Retrieves the current value of the year member variable as an integer.
Returns
The year.
Precondition
The date object must be fully constructed and initialized.
Postcondition
The object remains unchanged; the returned value reflects the current year.
Definition at line 51 of file Date.cpp.
{
    return m_year;
}
References m_year.
Referenced by operator<(), operator<<(), operator==(), operator>(), and TransferToBSTAndMap().
SetDay()
void Date::SetDay (int day)
Sets the value of the day variable.
Updates the day member variable to the specified value.
Parameters
day The new value of day as an integer.
Returns
void
Precondition
The date object must be fully constructed and initialized.
Postcondition
The m_day variable is updated to the value of the passed parameter day.
Definition at line 30 of file Date.cpp.
{
    m_day = day;
}
References m_day.
Referenced by ParseDateRecord().
SetMonth()
void Date::SetMonth (int month)
Sets the value of the month variable.
Updates the month member variable to the specified value.
Parameters
month The new value of month as an integer.
Returns
void
Precondition
The date object must be fully constructed and initialized.
Postcondition
The m_month variable is updated to the value of the passed parameter month.
Definition at line 44 of file Date.cpp.
{
    m_month = month;
}
References m_month.
Referenced by ParseDateRecord().
SetYear()
void Date::SetYear (int year)
Sets the value of the year variable.
Updates the year member variable to the specified value.
Parameters
year The new value of year as an integer.
Returns
void
Precondition
The date object must be fully constructed and initialized.
Postcondition
The m_year variable is updated to the value of the passed parameter year.
Definition at line 58 of file Date.cpp.
{
    m_year = year;
}
References m_year.
Referenced by ParseDateRecord().
Member Data Documentation
m_day
int Date::m_day private
Definition at line 118 of file Date.h.
Referenced by Date(), Date(), GetDay(), and SetDay().
m_month
int Date::m_month private
The day of the month as a number.
Definition at line 119 of file Date.h.
Referenced by Date(), Date(), GetMonth(), and SetMonth().
m_year
int Date::m_year private
The month as a number.
Definition at line 120 of file Date.h.
Referenced by Date(), Date(), GetYear(), and SetYear().
The documentation for this class was generated from the following files:
Date.h
Date.cpp